# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/db_pt_sofco_graha_gaji_id
spring.datasource.username=postgres
spring.datasource.password=

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Matikan Flyway
spring.flyway.enabled=false

# Biarkan Hibernate yang membuat/update tabel otomatis
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# temporary local
server.address=0.0.0.0
server.port=8080
